version: 0.2
env:
  variables:
    APP_NAME: "angular-cicd-pipeline-demo"
phases:
  install:
    runtime-versions:
      nodejs: 14.16.0
    commands:
      - npm ci
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 082272919318.dkr.ecr.eu-west-3.amazonaws.com
  build:
    commands:
      - docker build -t dj-website-frontend .
